using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;

namespace LargeFileViewer.View
{
    /// <summary>
    /// Interaction logic for CurrentViewState.xaml
    /// </summary>
    public partial class FileView : UserControl
    {
        public FileView()
        {
            InitializeComponent();
        }

        private void OnAutoGeneratedColumns(object sender, EventArgs e)
        {
            var dataGrid = sender as DataGrid;

            if(dataGrid == null)
                return;

            var rowNumberColumn = dataGrid.Columns.First(c => c.Header.Equals("Row #"));
            rowNumberColumn.Header = string.Empty;
            rowNumberColumn.CanUserSort = false;
        }
    }
}
